version: "3"

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/16
services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - db-data:/data/db
    ports:
      - 27017:27017
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: example

  web:
    image: webdevops/php-apache-dev:7.2
    ports:
      - 80:80
      - 443:443
      - 9000:9000
    volumes:
      - ./:/app
    environment:
      WEB_DOCUMENT_ROOT: /app/public
      XDEBUG_REMOTE_HOST: "172.16.0.1"
      XDEBUG_REMOTE_PORT: 9000
      XDEBUG_REMOTE_AUTOSTART: 1
      XDEBUG_REMOTE_CONNECT_BACK: 1

volumes:
  db-data: